LOG_PATH: /home/ywatanabe/proj/mngs_repo/.run_tests.sh.log
LOG_PATH_TMP: /home/ywatanabe/proj/mngs_repo/.run_tests.sh.log-tmp
Test run 1 of 1
[pytest]
pythonpath = .
testpaths =
    ./tests/mngs/plt
norecursedirs =
    *.egg
    .eggs
    dist
    build
    docs
    .tox
    .git
    __pycache__
    .old
python_files =
    test_*.py
    *_test.py
addopts =
    --import-mode=importlib
    -q
    --no-header
    --tb=short
    --exitfirst
    --verbose
    --color=yes
    -s
    --pdb
    --pdbcls=IPython.terminal.debugger:TerminalPdb
    # -n auto
    # --no-summary
env =
    PYTHONPATH=.
    TESTING=True
Thu May  1 08:20:08 AM AEST 2025
[1m============================= test session starts ==============================[0m

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[31mImportError while importing test module '/home/ywatanabe/proj/_mngs_repo/src/mngs/stats/tests/__corr_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
src/mngs/__init__.py:33: in <module>
    from . import gen
src/mngs/gen/__init__.py:28: in <module>
    module = importlib.import_module(f".{module_name}", package=__name__)
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/mngs/gen/_start.py:25: in <module>
    from ..plt._configure_mpl import configure_mpl
src/mngs/plt/__init__.py:13: in <module>
    from ._subplots._SubplotsWrapper import subplots
src/mngs/plt/_subplots/__init__.py:23: in <module>
    module = importlib.import_module(f".{module_name}", package=__name__)
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/mngs/plt/_subplots/_AxisWrapper.py:18: in <module>
    from ._AxisWrapperMixins import (AdjustmentMixin, BasicPlotMixin, SeabornMixin,
src/mngs/plt/_subplots/_AxisWrapperMixins/__init__.py:17: in <module>
    module = __importlib.import_module(f".{module_name}", package=__name__)
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/mngs/plt/_subplots/_AxisWrapperMixins/_MatplotlibPlotMixin_.py:24: in <module>
    from ....plt import ax as ax_module
src/mngs/plt/ax/__init__.py:23: in <module>
    from ._adjust._set_ticks import set_ticks
src/mngs/plt/ax/_adjust/_set_ticks.py:17: in <module>
    from ...dict._to_str import to_str
E   ModuleNotFoundError: No module named 'mngs.plt.dict'[0m
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> [0;32m/home/ywatanabe/.env-3.11/lib/python3.11/site-packages/_pytest/python.py[0m(523)[0;36mimporttestmodule[0;34m()[0m
[0;32m    521 [0;31m        )
[0m[0;32m    522 [0;31m        [0mformatted_tb[0m [0;34m=[0m [0mstr[0m[0;34m([0m[0mexc_repr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m--> 523 [0;31m        raise nodes.Collector.CollectError(
[0m[0;32m    524 [0;31m            [0;34mf"ImportError while importing test module '{path}'.\n"[0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m    525 [0;31m            [0;34m"Hint: make sure your test modules/packages have valid Python names.\n"[0m[0;34m[0m[0;34m[0m[0m
[0m
ipdb>






       ipdb>






       ipdb>                                                                                                                                                          

collected 0 items

!!!!!!!!!!!!!!!!!!! _pytest.outcomes.Exit: Quitting debugger !!!!!!!!!!!!!!!!!!!
[33m====================== [33mno tests ran[0m[33m in 105.61s (0:01:45)[0m[33m =======================[0m
