LOG_PATH: /home/ywatanabe/proj/mngs_repo/.run_tests.sh.log
LOG_PATH_TMP: /home/ywatanabe/proj/mngs_repo/.run_tests.sh.log-tmp
Test run 1 of 1
[pytest]
pythonpath = .
testpaths =
    ./tests/mngs/plt
norecursedirs =
    *.egg
    .eggs
    dist
    build
    docs
    .tox
    .git
    __pycache__
    .old
python_files =
    test_*.py
addopts =
    --import-mode=importlib
    -q
    --no-header
    --tb=short
    --last-failed    
    --exitfirst
    # --verbose
    --color=yes
    -s
    --pdb
    --pdbcls=IPython.terminal.debugger:TerminalPdb

    # -n auto
    # --no-summary
env =
    PYTHONPATH=.
    TESTING=True
Sun May 25 07:48:33 PM AEST 2025
/data/gpfs/projects/punim2354/ywatanabe/mngs_repo/tests/custom/test_matplotlib_compatibility.py
/data/gpfs/projects/punim2354/ywatanabe/mngs_repo/tests/custom/test_pip_install_latest.py
/data/gpfs/projects/punim2354/ywatanabe/mngs_repo/tests/custom/old/test_csv_export_with_index_handling.py
/data/gpfs/projects/punim2354/ywatanabe/mngs_repo/tests/custom/old/test_export_as_csv_comprehensive.py
/data/gpfs/projects/punim2354/ywatanabe/mngs_repo/tests/custom/old/test_export_as_csv_custom.py
/data/gpfs/projects/punim2354/ywatanabe/mngs_repo/tests/custom/old/test_export_as_csv_functionality.py
/data/gpfs/projects/punim2354/ywatanabe/mngs_repo/tests/custom/old/test_export_as_csv_matplotlib.py
/data/gpfs/projects/punim2354/ywatanabe/mngs_repo/tests/custom/old/test_export_as_csv_missing.py
/data/gpfs/projects/punim2354/ywatanabe/mngs_repo/tests/custom/old/test_export_as_csv_seaborn.py

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[31mImportError while importing test module '/data/gpfs/projects/punim2354/ywatanabe/mngs_repo/tests/custom/old/test_export_as_csv_custom.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/custom/old/test_export_as_csv_custom.py:18: in <module>
    from test_export_as_csv_utils import OUTPUT_DIR, verify_csv_export
E   ModuleNotFoundError: No module named 'test_export_as_csv_utils'[0m
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> [0;32m/home/ywatanabe/.env-3.10/lib/python3.10/site-packages/_pytest/python.py[0m(523)[0;36mimporttestmodule[0;34m()[0m
[0;32m    521 [0;31m        )
[0m[0;32m    522 [0;31m        [0mformatted_tb[0m [0;34m=[0m [0mstr[0m[0;34m([0m[0mexc_repr[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m--> 523 [0;31m        raise nodes.Collector.CollectError(
[0m[0;32m    524 [0;31m            [0;34mf"ImportError while importing test module '{path}'.\n"[0m[0;34m[0m[0;34m[0m[0m
[0m[0;32m    525 [0;31m            [0;34m"Hint: make sure your test modules/packages have valid Python names.\n"[0m[0;34m[0m[0;34m[0m[0m
[0m


!!!!!!!!!!!!!!!!!!! _pytest.outcomes.Exit: Quitting debugger !!!!!!!!!!!!!!!!!!!
[33m[33mno tests ran[0m[33m in 35.84s[0m[0m
